connections {
  remote-access {
    version = 2
    local_addrs = 10.10.0.4
    pools = remote-pool

    proposals = aes256-sha256-prfsha256-modp2048

    local {
      auth = pubkey
      certs = fullchain.pem
      id = vpn.example.com
    }

    remote {
      auth = pubkey
    }

    children {
      remote-access {
        local_ts = 10.10.0.0/16
        esp_proposals = aes256-sha256
        dpd_action = clear
      }
    }

    send_cert = always
    unique = never
  }

  site-b {
    version = 2
    local_addrs = 10.10.0.4
    remote_addrs = %any

    proposals = aes256-sha256-prfsha256-modp2048

    local {
      auth = pubkey
      certs = site-cert.pem
      id = vpn.example.com
    }

    remote {
      auth = pubkey
      id = site-b-router
    }

    children {
      site-b-cloud {
        local_ts = 10.10.0.0/24
        remote_ts = 10.10.2.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }

      site-b-site-a {
        local_ts = 10.10.1.0/24
        remote_ts = 10.10.2.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }

      site-b-remote-access {
        local_ts = 10.10.255.0/24
        remote_ts = 10.10.2.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }
    }

    send_cert = always
    unique = replace
  }

  site-a {
    version = 2
    local_addrs = 10.10.0.4
    remote_addrs = %any

    proposals = aes256-sha256-prfsha256-ecp256

    local {
      auth = pubkey
      certs = site-cert.pem
      id = vpn.example.com
    }

    remote {
      auth = pubkey
      id = site-a-router
    }

    children {

      site-a-cloud {
        local_ts = 10.10.0.0/24
        remote_ts = 10.10.1.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }

      site-a-site-b {
        local_ts = 10.10.2.0/24
        remote_ts = 10.10.1.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }

      site-a-remote-access {
        local_ts = 10.10.255.0/24
        remote_ts = 10.10.1.0/24
        esp_proposals = aes256-sha256
        dpd_action = restart
      }
    }

    send_cert = always
    unique = replace
  }

}

pools {
  remote-pool {
    addrs = 10.10.255.0/24
  }
}
